import { GuardWithAuth } from "@/features/auth/auth-guard";
import { SidebarAppLayout } from "@/features/root/app-layout";
import { AppRoot } from "@/features/root/app-root";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppRoot>
      <Suspense fallback={<div>Authenticating</div>}>
        <GuardWithAuth>
          <SidebarAppLayout>{children}</SidebarAppLayout>
        </GuardWithAuth>
      </Suspense>
    </AppRoot>
  );
}
